url: https://courses.stolley.co
uid: te
baseurl: /te/

course:
  number: COM 425/529
  title: Technical Editing
  tagline: >
    Online course covering theory and principles of editing through intensive applied practice.
  term: Spring 2020
  license:
    name: Creative Commons
    url: https://creativecommons.org/licenses/by/4.0/
  instructor:
    name: Karl Stolley
    full_title: Associate Professor of Digital Writing & Rhetoric
    honorific: Dr.
    title: Professsor
    url: https://stolley.co/
    github: https://github.com/karlstolley/
    email: karl.stolley@gmail.com
    office_hours: >
      Office hours via Basecamp Chat or Pings on Tuesdays, 4pm to 5pm, or by appointment or chance.
      I’m always signed into Basecamp and closely monitor my notifications. Message or email any
      time—I make students a priority, and I will repond as soon as I am able.

collections:
  - projects

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

highlighter: using_prism_thanks

exclude:
  - backstop_data
  - backstop.json
  - Rakefile
  - Gemfile*
