url: https://courses.stolley.co
baseurl: /wsi

course:
  number: ITMD 467/567
  title: Web Systems Integration
  tagline: >
    Enterprise-scale web development and web infrastructure to integrate server-side applications
    and databases with client-side rich internet applications in response to a defined business
    problem.
  term: Spring 2020
  instructor:
    name: Karl Stolley
    full_title: Associate Professor of Information Technology and Management
    honorific: Dr.
    title: Professsor
    url: https://stolley.co/
    email: karl.stolley@gmail.com
    office_hours: >
      Office hours via Basecamp Chat or Pings on Tuesdays, 4pm to 5pm, or by appointment or chance.
      I’m always signed into Basecamp and closely monitor my notifications. Message or email any
      time—I make students a priority, and I will repond as soon as I am able.

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

highlighter: using_prism_thanks

exclude:
  - backstop_data
  - backstop.json
  - Rakefile
  - Gemfile*
