#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)

require 'mercenary'
require 'jtoc'

Mercenary.program(:jtoc) do |p|
  p.version JTOpenCourse::VERSION
  p.description "A generator for the Open Course Jekyll theme"
  p.syntax "jt-gen <subcommand> [options]"
  p.command(:hello) do |c|
    c.description "Send a highly personal greeting to NAME"
    c.syntax "hello NAME"
    c.action do |args,options|
      puts "Hello, #{args.first}"
    end
  end

  p.command(:version) do |c|
    c.description "Ouput the version number"
    c.syntax "version"
    c.action do |_,_|
      puts JTOpenCourse::VERSION
    end
  end

  p.command(:new) do |c|
    c.description "Create a new Open-Course themed site"
    c.syntax "new COURSENAME"
    c.action do |args,_|
      course = JTOpenCourse::SiteBuilder.new(args.first)
      if course.path.exist?
        puts "A directory named '#{course.name}' already exists. Aborting"
        abort
      end
      course.create!
    end
  end

  p.action do |args, _|
    if args.empty?
      puts p
    else
      subcommand = args.first
      unless p.has_command? subcommand
        puts "Sorry, I don't know how to '#{args.first}'."
        puts "Try running `jtgen --help` for help."
      end
    end
  end
end
